project:
  type: website
  output-dir: docs

website:
  open-graph: true
  site-url: https://skywes.github.io/portfolio/
  search: false
  navbar:
    left: 
      - text: Skylar Carroll
        href: about.qmd
      - text: Projects
        href: index.qmd
      - text: About
        href: about.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/skylar-carroll/
      - icon: github
        href: https://github.com/SkyWes?tab=repositories
      - icon: envelope
        href: mailto:86sky.c@gmail.com
        
  page-footer: 
    left: "© 2024, Skylar Carroll" 
    right: 
      - href: index.qmd
        text: Projects
      - icon: linkedin
        href: https://www.linkedin.com/in/skylar-carroll/
      - icon: github
        href: https://github.com/SkyWes?tab=repositories
      - icon: envelope
        href: mailto:86sky.c@gmail.com

format:
  html:
    theme: flatly
    css: styles.css

editor: visual

